ISS-924 Add Dependency FAQ
pixee/docs pull request #186
Opened 2024-08-08 15:34 UTC by dhafley

2024-08-08 15:39 UTC, dhafley commented
/close iss-925

2024-08-08 16:00 UTC, drdavella requested changes

2024-08-08 16:00 UTC, drdavella commented on docs/faqs.md
> +We always prefer to use existing controls built into a language, or a control from a well-known and trusted community dependency. When this is not an option, we add our own open source dependency to
Our own security packages are MIT but this is not strictly true as Python adds some third-party packages with other permissive licenses. 
```suggestion
We always prefer to use existing controls built into a language, or a control from a well-known and trusted community dependency. When this is not an option, we add our own open source dependency to the project to ensure maximum readability and maintainability. All dependencies utilize permissive open-source licenses.
```

2024-08-08 16:34 UTC, drdavella approved these changes

2024-08-09 10:03 UTC, gilday approved these changes

2024-08-09 10:03 UTC, gilday commented on docs/faqs.md
> +### Why does pixee sometimes add new dependencies to my project?
Uppercase Pixee for consistency

2024-08-09 10:03 UTC, gilday commented on docs/faqs.md
> +We always prefer to use existing controls built into a language, or a control from a well-known and trusted community dependency. When this is not an option, we add our own open source dependency to
Consider expanding on "when this is not an option". Why is not an option? Maybe "when no such dependency exists that meets that criteria"

2024-08-09 10:03 UTC, gilday commented on docs/faqs.md
> +Learn more about the [Java Security Toolkit (io.github.pixee.java-security-toolkit) on Maven Central](https://central.sonatype.com/artifact/io.github.pixee/java-security-toolkit/overview).
There's another Java toolkit we maintain specifically for xstream.

2024-08-09 12:17 UTC, merged